In [2]:
#Numpy

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
array=np.array([1,2,3,4,5,6,7,8])
print("Numpy array",array)
print("Type", type(array))

Numpy array [1 2 3 4 5 6 7 8]
Type <class 'numpy.ndarray'>


In [6]:
#2 dimensional arrays
array2=np.array([[1,2,3],[4,5,6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
type(array2)

numpy.ndarray

# Built in Function



In [11]:
zeroarray = np.zeros((3,4))
zeroarray

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
onesarray=np.ones((3,5))
onesarray

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
identity=np.eye(6)
identity

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Initializing Numpy array using tuple

In [16]:
listarray=np.array([4,5,3])
listarray

array([4, 5, 3])

In [17]:
tuplesarray=np.array((1,4,5,3))
tuplesarray

array([1, 4, 5, 3])

In [18]:
print(listarray.shape)

(3,)


In [19]:
#Dimensions
array2.ndim

2

In [20]:
#Reshaping array to differnt dimensions
listarray

array([4, 5, 3])

In [27]:
listarray.reshape(3,1)

array([[4],
       [5],
       [3]])

In [29]:
data = np.array([10, 15, 20, 25, 30])
print("Mean:", np.mean(data))
print("Median:",np.median(data))
print("Standard Deviation:",np.std(data))

Mean: 20.0
Median: 20.0
Standard Deviation: 7.0710678118654755
